version: '3'
services:
    yolov1:
        runtime: nvidia
        user: $UID:$GID
        build:
            context: .
            args:
                UID: $UID
                GID: $GID
                UNAME: $UNAME
        shm_size: '2gb'
        volumes:
            - ./src:/src
            - ./res:/res
            - ../RawData/resize_images:/images
        command: sh /src/run.sh
        # command: python /src/dataset.py
